### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/yaml-completion-helper#2]
Currently, we only support completions on root level. Now, we need to implement support for arrays. For instance, to get intellisense for things like

```yaml
parameters:
   - pass-as: --learning_rate=5
   - pass-as: --max_steps=200
```

Where we should get intellisense for the keywords inside an array item.
